import type{FastifyInstance}from"fastify";import{z}from"zod";import{pool,tx}from"../db.js";import{createSession,hashPassword,verifyPassword,requireAuth}from"../auth.js";import{createHash,timingSafeEqual}from"node:crypto";import{config}from"../config.js";import{securityEvent}from"../security.js";
const login=z.object({username:z.string().trim().min(3).max(64),password:z.string().min(8).max(128)}),strong=z.string().min(12).max(128).regex(/[a-z]/,"PASSWORD_LOWERCASE_REQUIRED").regex(/[A-Z]/,"PASSWORD_UPPERCASE_REQUIRED").regex(/\d/,"PASSWORD_DIGIT_REQUIRED"),attempts=new Map<string,{n:number;until:number}>();function blocked(ip:string){const x=attempts.get(ip),now=Date.now();if(!x||x.until<now){attempts.set(ip,{n:0,until:now+900000});return false}return x.n>=10}function fail(ip:string){const x=attempts.get(ip);if(x)x.n++}function secretOk(v?:string){if(!config.BOOTSTRAP_SECRET)return config.NODE_ENV!=="production";if(!v)return false;const a=Buffer.from(v),b=Buffer.from(config.BOOTSTRAP_SECRET);return a.length===b.length&&timingSafeEqual(a,b)}
export async function registerAuthRoutes(app:FastifyInstance){
app.get("/auth/status",async()=>{const q=await pool.query("SELECT EXISTS(SELECT 1 FROM users) bootstrapped");return{bootstrapped:Boolean(q.rows[0].bootstrapped),bootstrapSecretRequired:Boolean(config.BOOTSTRAP_SECRET)}});
app.get("/auth/me",{preHandler:requireAuth},async req=>({user:req.actor}));
app.post("/auth/bootstrap",async(req,reply)=>{if(blocked(req.ip))return reply.code(429).send({error:"RATE_LIMITED"});const b=login.extend({password:strong,displayName:z.string().trim().min(2).max(100),installSecret:z.string().optional()}).parse(req.body);if(!secretOk(b.installSecret??req.headers["x-bootstrap-secret"]as string|undefined)){fail(req.ip);return reply.code(403).send({error:"INVALID_BOOTSTRAP_SECRET"})}const passwordHash=await hashPassword(b.password),created=await tx(async c=>{await c.query("SELECT pg_advisory_xact_lock($1)",[731904]);if((await c.query("SELECT 1 FROM users LIMIT 1")).rowCount)return false;const q=await c.query("INSERT INTO users(username,display_name,password_hash,role,position,password_changed_at)VALUES($1,$2,$3,'admin','ceo',now())RETURNING id",[b.username.toLowerCase(),b.displayName,passwordHash]);await createSession(q.rows[0].id,reply,c);return true});if(!created)return reply.code(409).send({error:"ALREADY_BOOTSTRAPPED"});attempts.delete(req.ip);return{ok:true}});
app.post("/auth/login",async(req,reply)=>{if(blocked(req.ip))return reply.code(429).send({error:"RATE_LIMITED"});const b=login.parse(req.body),username=b.username.toLowerCase(),q=await pool.query("SELECT * FROM users WHERE username=$1",[username]);if(!q.rowCount||!q.rows[0].active){fail(req.ip);await securityEvent("login.failure",req,{reason:q.rowCount?"inactive":"unknown_user"},q.rows[0]?.id??null,username);return reply.code(401).send({error:"INVALID_CREDENTIALS"})}const u=q.rows[0];if(u.locked_until&&new Date(u.locked_until)>new Date()){await securityEvent("login.blocked",req,{lockedUntil:u.locked_until},u.id,username,"critical");return reply.code(423).send({error:"ACCOUNT_LOCKED",lockedUntil:u.locked_until})}if(!await verifyPassword(u.password_hash,b.password)){fail(req.ip);const r=await pool.query("UPDATE users SET failed_login_count=failed_login_count+1,locked_until=CASE WHEN failed_login_count+1>=5 THEN now()+interval '15 minutes' ELSE NULL END WHERE id=$1 RETURNING failed_login_count,locked_until",[u.id]);await securityEvent(r.rows[0].locked_until?"account.locked":"login.failure",req,{failedCount:r.rows[0].failed_login_count},u.id,username,r.rows[0].locked_until?"critical":"warning");return reply.code(401).send({error:"INVALID_CREDENTIALS"})}attempts.delete(req.ip);await pool.query("UPDATE users SET failed_login_count=0,locked_until=NULL WHERE id=$1",[u.id]);await createSession(u.id,reply);await securityEvent("login.success",req,{},u.id,username,"info");return{ok:true,role:u.role,mustChangePassword:u.must_change_password}});
app.post("/auth/change-password",{preHandler:requireAuth},async(req,reply)=>{const b=z.object({currentPassword:z.string().min(8).max(128),newPassword:strong}).parse(req.body),u=await pool.query("SELECT password_hash,username FROM users WHERE id=$1 AND active",[req.actor!.id]);if(!u.rowCount||!await verifyPassword(u.rows[0].password_hash,b.currentPassword))return reply.code(400).send({error:"CURRENT_PASSWORD_INVALID"});if(await verifyPassword(u.rows[0].password_hash,b.newPassword))return reply.code(400).send({error:"PASSWORD_REUSE_FORBIDDEN"});await tx(async c=>{await c.query("UPDATE users SET password_hash=$2,password_changed_at=now(),must_change_password=false WHERE id=$1",[req.actor!.id,await hashPassword(b.newPassword)]);await c.query("DELETE FROM sessions WHERE user_id=$1",[req.actor!.id]);await c.query("INSERT INTO audit_logs(actor_id,action,entity_type,entity_id,details)VALUES($1,'user.password.change','user',$1,'{}')",[req.actor!.id])});reply.clearCookie("sid",{path:"/"});return{changed:true,loginRequired:true}});
app.post("/auth/logout",{preHandler:requireAuth},async(req,reply)=>{const sid=req.cookies.sid;if(sid)await pool.query("DELETE FROM sessions WHERE token_hash=$1",[createHash("sha256").update(sid).digest("hex")]);reply.clearCookie("sid",{path:"/"});return{ok:true}})
}
