import type{FastifyInstance}from"fastify";import{readFile}from"node:fs/promises";import{resolve}from"node:path";import{z}from"zod";import{allow,requireAuth}from"../auth.js";import{pool,tx}from"../db.js";
const modules=[
{code:"system-admin",title:"راهنمای مدیر سیستم",positions:["ceo"],roles:["admin"],file:"SYSTEM_ADMIN.md",topics:["کاربران و دسترسی","امنیت","مانیتورینگ","Backup و Restore","مدیریت رخداد"]},
{code:"ceo",title:"راهنمای مدیرعامل",positions:["ceo"],roles:["admin"],file:"CEO.md",topics:["داشبورد مدیریتی","تصمیم و تأیید","گزارش‌ها","Audit"]},
{code:"supervision",title:"راهنمای معاون سرپرستی",positions:["supervision_deputy"],roles:["admin"],file:"SUPERVISION.md",topics:["گزارش هفتگی","اقدامات","عملکرد رابط","هشدارها"]},
{code:"liaison",title:"راهنمای رابط",positions:["liaison"],roles:["admin"],file:"LIAISON.md",topics:["خانواده و سرپرست","گزارش هفتگی","پیشنهاد اقدام","درخواست مالی"]},
{code:"health-education",title:"راهنمای درمان و آموزش",positions:["health_officer","education_officer","health_deputy","education_deputy"],roles:["admin"],file:"SPECIALISTS.md",topics:["ارجاع تخصصی","پرونده درمان","پرونده آموزش","اسناد حساس"]},
{code:"finance",title:"راهنمای مسئول مالی",positions:["finance_officer","finance_deputy"],roles:["accountant","admin"],file:"FINANCE.md",topics:["کارتابل مالی","بودجه","پرداخت","رسید"]},
{code:"migration",title:"راهنمای مهاجرت داده",positions:["ceo"],roles:["admin"],file:"DATA_MIGRATION.md",topics:["قالب Excel","Preview","رفع خطا","تطبیق"]},
{code:"uat",title:"راهنمای UAT",positions:["ceo","supervision_deputy","liaison","health_officer","education_officer","finance_officer"],roles:["admin","caseworker","accountant"],file:"UAT.md",topics:["سناریوها","ثبت نتیجه","بازخورد","Release Candidate"]}
]as const;
const canSee=(a:{role:string;position:string},m:(typeof modules)[number])=>a.role==="admin"||(m.roles as readonly string[]).includes(a.role)||(m.positions as readonly string[]).includes(a.position);
export async function registerTrainingRoutes(app:FastifyInstance){app.addHook("preHandler",requireAuth);
app.get("/training/modules",async req=>{const a=await pool.query("SELECT module_code,acknowledged_at FROM training_acknowledgements WHERE user_id=$1",[req.actor!.id]),ack=new Map(a.rows.map(x=>[x.module_code,x.acknowledged_at]));return{modules:modules.filter(m=>canSee(req.actor!,m)).map(m=>({...m,acknowledgedAt:ack.get(m.code)??null,documentUrl:`/api/training/modules/${m.code}/document`}))}});
app.get("/training/modules/:code/document",async(req,reply)=>{const code=z.string().max(80).parse((req.params as{code:string}).code),m=modules.find(x=>x.code===code);if(!m)return reply.code(404).send({error:"TRAINING_MODULE_NOT_FOUND"});if(!canSee(req.actor!,m))return reply.code(403).send({error:"FORBIDDEN"});const content=await readFile(resolve(process.cwd(),"docs/training",m.file),"utf8");return{code:m.code,title:m.title,content}});
app.post("/training/modules/:code/acknowledge",async(req,reply)=>{const code=z.string().max(80).parse((req.params as{code:string}).code),m=modules.find(x=>x.code===code);if(!m)return reply.code(404).send({error:"TRAINING_MODULE_NOT_FOUND"});if(!canSee(req.actor!,m))return reply.code(403).send({error:"FORBIDDEN"});await tx(async c=>{await c.query("INSERT INTO training_acknowledgements(user_id,module_code)VALUES($1,$2)ON CONFLICT(user_id,module_code)DO UPDATE SET acknowledged_at=now()",[req.actor!.id,code]);await c.query("INSERT INTO audit_logs(actor_id,action,entity_type,details)VALUES($1,'training.acknowledge','training',$2)",[req.actor!.id,{moduleCode:code}])});return{moduleCode:code,acknowledged:true}});
app.get("/training/progress",{preHandler:allow("admin")},async()=>{const users=await pool.query(`SELECT u.id,u.display_name "displayName",u.username,u.role,u.position,count(a.id)::int acknowledged FROM users u LEFT JOIN training_acknowledgements a ON a.user_id=u.id WHERE u.active GROUP BY u.id ORDER BY u.display_name`);return{users:users.rows.map(u=>({...u,required:modules.filter(m=>canSee(u,m)).length}))}});
app.get("/handover/checklist",{preHandler:allow("admin")},async()=>{const q=await pool.query(`SELECT h.item_code "code",h.title,h.required,h.completed,h.completed_at "completedAt",h.evidence_note "evidenceNote",u.display_name "completedBy" FROM handover_checklist_items h LEFT JOIN users u ON u.id=h.completed_by ORDER BY h.item_code`),required=q.rows.filter(x=>x.required),done=required.filter(x=>x.completed).length;return{items:q.rows,summary:{required:required.length,completed:done,ready:done===required.length}}});
app.put("/handover/checklist/:code",{preHandler:allow("admin")},async(req,reply)=>{const code=z.string().max(80).parse((req.params as{code:string}).code),b=z.object({completed:z.boolean(),evidenceNote:z.string().max(2000).default("")}).parse(req.body),q=await pool.query("UPDATE handover_checklist_items SET completed=$2::boolean,completed_by=CASE WHEN $2::boolean THEN $3::uuid ELSE NULL END,completed_at=CASE WHEN $2::boolean THEN now() ELSE NULL END,evidence_note=$4::text,updated_at=now() WHERE item_code=$1 RETURNING item_code",[code,b.completed,req.actor!.id,b.evidenceNote]);if(!q.rowCount)return reply.code(404).send({error:"HANDOVER_ITEM_NOT_FOUND"});await pool.query("INSERT INTO audit_logs(actor_id,action,entity_type,details)VALUES($1,'handover.checklist.update','handover',$2)",[req.actor!.id,{itemCode:code,...b}]);return{code,completed:b.completed}})
}
