import type{FastifyInstance}from"fastify";import{z}from"zod";import{allow,requireAuth}from"../auth.js";import{pool,tx}from"../db.js";
const uuid=z.string().uuid();
const defaults=[
["CEO-01","ceo","مرور داشبورد و تصمیم مدیریتی",["ورود به داشبورد مدیرعامل","بررسی هشدارهای بحرانی","بازکردن پرونده جامع","بررسی و تصمیم روی درخواست"],"داده‌های مدیریتی صحیح و تصمیم در Audit ثبت شود"],
["SUP-01","supervision_deputy","چرخه کامل سرپرستی و اقدام",["بررسی گزارش هفتگی","تأیید گزارش","تخصیص اقدام و مهلت","بررسی نتیجه اقدام"],"گزارش و اقدام مطابق گردش مصوب بسته شود"],
["LIA-01","liaison","ثبت خانواده و گزارش هفتگی",["ایجاد خانواده","انتخاب سرپرست","ثبت گزارش هفتگی","پیشنهاد اقدام"],"داده‌ها برای تأیید معاون ارسال و خارج از محدوده قابل مشاهده نباشد"],
["HLT-01","health_officer","رسیدگی پرونده درمان",["بازکردن ارجاع درمانی","ثبت ارزیابی و نوبت","افزودن مدرک پزشکی","ثبت نتیجه"],"پرونده درمان کامل و دسترسی حساس کنترل شود"],
["EDU-01","education_officer","رسیدگی پرونده آموزش",["بازکردن ارجاع آموزشی","ثبت وضعیت تحصیلی","ثبت برنامه حمایتی","ارزیابی نتیجه"],"گردش آموزش تا تکمیل اجرا شود"],
["FIN-01","finance_officer","پرداخت درخواست مصوب",["مشاهده کارتابل مالی","کنترل بودجه صندوق","ثبت پرداخت و رسید","بررسی تاریخچه خانواده"],"پرداخت یک‌بار انجام و بودجه و رسید صحیح ثبت شود"],
["E2E-01","supervision_deputy","سناریوی سراسری خانواده تا پرداخت",["ایجاد خانواده و تخصیص سرپرست","گزارش هفتگی و تأیید","اقدام درمانی و تخصیص مسئول","ثبت نتیجه درمان","درخواست مالی و پرداخت","بستن اقدام"],"تمام زنجیره با Audit و کنترل دسترسی صحیح تکمیل شود"]
]as const;
const management=(a:{role:string;position:string})=>a.role==="admin"||["ceo","supervision_deputy"].includes(a.position);
export async function registerUatRoutes(app:FastifyInstance){app.addHook("preHandler",requireAuth);
app.post("/uat/cycles",{preHandler:allow("admin")},async(req,reply)=>{const b=z.object({name:z.string().trim().min(3).max(150),targetVersion:z.string().trim().min(2).max(40),includeDefaults:z.boolean().default(true)}).parse(req.body),id=await tx(async c=>{const q=await c.query("INSERT INTO uat_cycles(name,target_version,created_by)VALUES($1,$2,$3)RETURNING id",[b.name,b.targetVersion,req.actor!.id]);if(b.includeDefaults)for(const[dcode,position,title,steps,expected]of defaults)await c.query("INSERT INTO uat_scenarios(cycle_id,code,position,title,steps,expected_result,priority)VALUES($1,$2,$3,$4,$5,$6,$7)",[q.rows[0].id,dcode,position,title,JSON.stringify(steps),expected,dcode==="E2E-01"?"critical":"high"]);await c.query("INSERT INTO audit_logs(actor_id,action,entity_type,entity_id,details)VALUES($1,'uat.cycle.create','uat_cycle',$2,$3)",[req.actor!.id,q.rows[0].id,{name:b.name,targetVersion:b.targetVersion,defaultScenarios:b.includeDefaults?defaults.length:0}]);return q.rows[0].id});return reply.code(201).send({cycleId:id,scenariosCreated:b.includeDefaults?defaults.length:0})});
app.post("/uat/cycles/:id/activate",{preHandler:allow("admin")},async(req,reply)=>{const id=uuid.parse((req.params as{id:string}).id),q=await pool.query("UPDATE uat_cycles SET status='active',starts_at=COALESCE(starts_at,now()),updated_at=now() WHERE id=$1 AND status='draft' RETURNING id",[id]);if(!q.rowCount)return reply.code(409).send({error:"UAT_CYCLE_NOT_ACTIVATABLE"});await pool.query("INSERT INTO audit_logs(actor_id,action,entity_type,entity_id,details)VALUES($1,'uat.cycle.activate','uat_cycle',$2,'{}')",[req.actor!.id,id]);return{cycleId:id,status:"active"}});
app.get("/uat/cycles",async(req)=>{const filter=management(req.actor!)?"":"WHERE c.status='active'",q=await pool.query(`SELECT c.id,c.name,c.target_version "targetVersion",c.status,c.starts_at "startsAt",c.ends_at "endsAt",c.release_candidate_version "releaseCandidateVersion",count(s.id)::int scenarios FROM uat_cycles c LEFT JOIN uat_scenarios s ON s.cycle_id=c.id ${filter} GROUP BY c.id ORDER BY c.created_at DESC`);return{cycles:q.rows}});
app.get("/uat/cycles/:id/scenarios",async(req,reply)=>{const id=uuid.parse((req.params as{id:string}).id),cycle=await pool.query("SELECT status FROM uat_cycles WHERE id=$1",[id]);if(!cycle.rowCount)return reply.code(404).send({error:"UAT_CYCLE_NOT_FOUND"});if(cycle.rows[0].status==="draft"&&!management(req.actor!))return reply.code(403).send({error:"FORBIDDEN"});const all=management(req.actor!),q=await pool.query(`SELECT s.id,s.code,s.position,s.title,s.steps,s.expected_result "expectedResult",s.priority,s.required,r.status "myStatus",r.notes "myNotes",r.tested_at "testedAt" FROM uat_scenarios s LEFT JOIN uat_results r ON r.scenario_id=s.id AND r.tester_id=$2 WHERE s.cycle_id=$1 ${all?'':'AND s.position=$3'} ORDER BY CASE s.priority WHEN 'critical' THEN 0 WHEN 'high' THEN 1 WHEN 'normal' THEN 2 ELSE 3 END,s.code`,all?[id,req.actor!.id]:[id,req.actor!.id,req.actor!.position]);return{scenarios:q.rows}});
app.put("/uat/scenarios/:id/result",async(req,reply)=>{const id=uuid.parse((req.params as{id:string}).id),b=z.object({status:z.enum(["passed","failed","blocked"]),notes:z.string().trim().max(4000).default(""),evidence:z.record(z.unknown()).default({})}).parse(req.body),s=await pool.query("SELECT s.*,c.status cycle_status FROM uat_scenarios s JOIN uat_cycles c ON c.id=s.cycle_id WHERE s.id=$1",[id]);if(!s.rowCount)return reply.code(404).send({error:"UAT_SCENARIO_NOT_FOUND"});if(s.rows[0].cycle_status!=="active")return reply.code(409).send({error:"UAT_CYCLE_NOT_ACTIVE"});if(!management(req.actor!)&&s.rows[0].position!==req.actor!.position)return reply.code(403).send({error:"UAT_ROLE_MISMATCH"});await tx(async c=>{await c.query(`INSERT INTO uat_results(scenario_id,tester_id,status,notes,evidence)VALUES($1,$2,$3,$4,$5)ON CONFLICT(scenario_id,tester_id)DO UPDATE SET status=EXCLUDED.status,notes=EXCLUDED.notes,evidence=EXCLUDED.evidence,tested_at=now()`,[id,req.actor!.id,b.status,b.notes,b.evidence]);await c.query("INSERT INTO audit_logs(actor_id,action,entity_type,entity_id,details)VALUES($1,'uat.result.submit','uat_scenario',$2,$3)",[req.actor!.id,id,{status:b.status,cycleId:s.rows[0].cycle_id}])});return{scenarioId:id,status:b.status}});
app.post("/uat/feedback",async(req,reply)=>{const b=z.object({cycleId:uuid,scenarioId:uuid.nullable().optional(),category:z.enum(["defect","improvement","ux","training"]),severity:z.enum(["low","normal","high","critical"]),title:z.string().trim().min(3).max(200),description:z.string().trim().min(3).max(5000)}).parse(req.body),cycle=await pool.query("SELECT status FROM uat_cycles WHERE id=$1",[b.cycleId]);if(!cycle.rowCount)return reply.code(404).send({error:"UAT_CYCLE_NOT_FOUND"});if(cycle.rows[0].status!=="active")return reply.code(409).send({error:"UAT_CYCLE_NOT_ACTIVE"});if(b.scenarioId&&!(await pool.query("SELECT 1 FROM uat_scenarios WHERE id=$1 AND cycle_id=$2",[b.scenarioId,b.cycleId])).rowCount)return reply.code(400).send({error:"UAT_SCENARIO_CYCLE_MISMATCH"});const q=await pool.query("INSERT INTO uat_feedback(cycle_id,scenario_id,reported_by,category,severity,title,description)VALUES($1,$2,$3,$4,$5,$6,$7)RETURNING id",[b.cycleId,b.scenarioId??null,req.actor!.id,b.category,b.severity,b.title,b.description]);return reply.code(201).send({feedbackId:q.rows[0].id})});
app.get("/uat/cycles/:id/summary",async(req,reply)=>{if(!management(req.actor!))return reply.code(403).send({error:"FORBIDDEN"});const id=uuid.parse((req.params as{id:string}).id),cycle=await pool.query("SELECT * FROM uat_cycles WHERE id=$1",[id]);if(!cycle.rowCount)return reply.code(404).send({error:"UAT_CYCLE_NOT_FOUND"});const[results,feedback,positions]=await Promise.all([pool.query(`SELECT s.position,s.code,s.title,r.status,r.tested_at "testedAt",u.display_name "testerName" FROM uat_scenarios s LEFT JOIN LATERAL(SELECT * FROM uat_results x WHERE x.scenario_id=s.id ORDER BY tested_at DESC LIMIT 1)r ON true LEFT JOIN users u ON u.id=r.tester_id WHERE s.cycle_id=$1 ORDER BY s.code`,[id]),pool.query(`SELECT f.id,f.category,f.severity,f.title,f.description,f.status,f.priority_rank "priorityRank",f.resolution_note "resolutionNote",f.created_at "createdAt",u.display_name "reportedBy" FROM uat_feedback f LEFT JOIN users u ON u.id=f.reported_by WHERE f.cycle_id=$1 ORDER BY CASE f.severity WHEN 'critical' THEN 0 WHEN 'high' THEN 1 WHEN 'normal' THEN 2 ELSE 3 END,COALESCE(f.priority_rank,999),f.created_at`,[id]),pool.query(`SELECT s.position,count(*) FILTER(WHERE r.status='passed')::int passed,count(*)::int required FROM uat_scenarios s LEFT JOIN LATERAL(SELECT status FROM uat_results x WHERE x.scenario_id=s.id ORDER BY tested_at DESC LIMIT 1)r ON true WHERE s.cycle_id=$1 AND s.required GROUP BY s.position`,[id])]);const criticalOpen=feedback.rows.filter(x=>x.severity==="critical"&&!['fixed','closed'].includes(x.status)).length,requiredPassed=results.rows.filter(x=>x.status==="passed").length===results.rowCount,roleCoverage=positions.rows.every(x=>x.passed>0),ready=requiredPassed&&roleCoverage&&criticalOpen===0;return{cycle:cycle.rows[0],results:results.rows,feedback:feedback.rows,roleCoverage:positions.rows,readiness:{ready,requiredPassed,allRolesCovered:roleCoverage,criticalOpen}}});
app.patch("/uat/feedback/:id",async(req,reply)=>{if(!management(req.actor!))return reply.code(403).send({error:"FORBIDDEN"});const id=uuid.parse((req.params as{id:string}).id),b=z.object({status:z.enum(["open","triaged","fixed","deferred","closed"]),priorityRank:z.coerce.number().int().min(1).max(999).nullable().optional(),resolutionNote:z.string().max(3000).default("")}).parse(req.body),q=await pool.query("UPDATE uat_feedback SET status=$2,priority_rank=$3,resolution_note=$4,updated_at=now() WHERE id=$1 RETURNING cycle_id",[id,b.status,b.priorityRank??null,b.resolutionNote]);if(!q.rowCount)return reply.code(404).send({error:"UAT_FEEDBACK_NOT_FOUND"});await pool.query("INSERT INTO audit_logs(actor_id,action,entity_type,entity_id,details)VALUES($1,'uat.feedback.triage','uat_feedback',$2,$3)",[req.actor!.id,id,b]);return{feedbackId:id,status:b.status}});
app.post("/uat/cycles/:id/release-candidate",{preHandler:allow("admin")},async(req,reply)=>{const id=uuid.parse((req.params as{id:string}).id),b=z.object({version:z.string().trim().regex(/^v?\d+\.\d+\.\d+(-rc\.\d+)?$/)}).parse(req.body),[missing,critical]=await Promise.all([pool.query(`SELECT count(*)::int n FROM uat_scenarios s WHERE s.cycle_id=$1 AND s.required AND NOT EXISTS(SELECT 1 FROM uat_results r WHERE r.scenario_id=s.id AND r.status='passed')`,[id]),pool.query("SELECT count(*)::int n FROM uat_feedback WHERE cycle_id=$1 AND severity='critical' AND status NOT IN ('fixed','closed')",[id])]);if(missing.rows[0].n||critical.rows[0].n)return reply.code(409).send({error:"UAT_NOT_READY",missingScenarios:missing.rows[0].n,criticalOpen:critical.rows[0].n});const q=await pool.query("UPDATE uat_cycles SET status='release_candidate',release_candidate_version=$2,ends_at=now(),updated_at=now() WHERE id=$1 AND status='active' RETURNING id",[id,b.version]);if(!q.rowCount)return reply.code(409).send({error:"UAT_CYCLE_NOT_ACTIVE"});await pool.query("INSERT INTO audit_logs(actor_id,action,entity_type,entity_id,details)VALUES($1,'uat.release_candidate','uat_cycle',$2,$3)",[req.actor!.id,id,{version:b.version}]);return{cycleId:id,status:"release_candidate",version:b.version}})
}
