-- C.14 future extensions: donors, allocations, inventory, notification outbox, public requests and geography.
CREATE TABLE donors(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),name text NOT NULL,donor_type text NOT NULL CHECK(donor_type IN('individual','organization')),phone text NOT NULL DEFAULT '',email text NOT NULL DEFAULT '',notes text NOT NULL DEFAULT '',active boolean NOT NULL DEFAULT true,created_by uuid REFERENCES users(id),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE donations(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),donor_id uuid NOT NULL REFERENCES donors(id),donation_type text NOT NULL CHECK(donation_type IN('cash','in_kind')),amount bigint CHECK(amount IS NULL OR amount>0),description text NOT NULL DEFAULT '',status text NOT NULL DEFAULT 'pledged' CHECK(status IN('pledged','received','allocated','cancelled')),received_at timestamptz,fund_id uuid REFERENCES funds(id),created_by uuid REFERENCES users(id),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),CHECK((donation_type='cash' AND amount IS NOT NULL) OR donation_type='in_kind'));
CREATE TABLE donation_allocations(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),donation_id uuid NOT NULL REFERENCES donations(id),family_id uuid NOT NULL REFERENCES families(id),amount bigint CHECK(amount IS NULL OR amount>0),quantity numeric(14,3) CHECK(quantity IS NULL OR quantity>0),note text NOT NULL DEFAULT '',allocated_by uuid REFERENCES users(id),created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX donation_allocations_donation_idx ON donation_allocations(donation_id);
CREATE INDEX donations_donor_idx ON donations(donor_id,created_at);
CREATE TABLE inventory_items(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),name text UNIQUE NOT NULL,unit text NOT NULL,minimum_stock numeric(14,3) NOT NULL DEFAULT 0 CHECK(minimum_stock>=0),active boolean NOT NULL DEFAULT true,created_by uuid REFERENCES users(id),created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE inventory_transactions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),item_id uuid NOT NULL REFERENCES inventory_items(id),transaction_type text NOT NULL CHECK(transaction_type IN('receipt','issue','adjustment_in','adjustment_out')),quantity numeric(14,3) NOT NULL CHECK(quantity>0),family_id uuid REFERENCES families(id),donation_id uuid REFERENCES donations(id),note text NOT NULL DEFAULT '',created_by uuid REFERENCES users(id),created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX inventory_transactions_item_idx ON inventory_transactions(item_id,created_at);
CREATE TABLE notification_outbox(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),channel text NOT NULL CHECK(channel IN('in_app','sms','email')),recipient text NOT NULL,template_key text NOT NULL,payload jsonb NOT NULL DEFAULT '{}',status text NOT NULL DEFAULT 'queued' CHECK(status IN('queued','sent','failed','cancelled')),attempts int NOT NULL DEFAULT 0,last_error text,created_by uuid REFERENCES users(id),created_at timestamptz NOT NULL DEFAULT now(),sent_at timestamptz);
CREATE INDEX notification_outbox_status_idx ON notification_outbox(status,created_at);
CREATE TABLE public_support_requests(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tracking_code text UNIQUE NOT NULL,applicant_name text NOT NULL,phone text NOT NULL,national_id text,summary text NOT NULL,status text NOT NULL DEFAULT 'new' CHECK(status IN('new','reviewing','accepted','rejected','closed')),decision_note text NOT NULL DEFAULT '',reviewed_by uuid REFERENCES users(id),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),CHECK(national_id IS NULL OR national_id ~ '^\d{10}$'));
CREATE INDEX public_support_requests_status_idx ON public_support_requests(status,created_at);
ALTER TABLE families ADD COLUMN latitude numeric(9,6) CHECK(latitude IS NULL OR latitude BETWEEN -90 AND 90);
ALTER TABLE families ADD COLUMN longitude numeric(9,6) CHECK(longitude IS NULL OR longitude BETWEEN -180 AND 180);
