import{createHash}from"node:crypto";
import type{FastifyRequest}from"fastify";
import type{PoolClient}from"pg";
import{pool}from"./db.js";
export const MAX_FILE_BYTES=8*1024*1024;
export function passwordIssues(v:string){const issues:string[]=[];if(v.length<12||v.length>128)issues.push("length");if(!/[a-z]/.test(v))issues.push("lowercase");if(!/[A-Z]/.test(v))issues.push("uppercase");if(!/\d/.test(v))issues.push("digit");return issues}
export function inspectFile(data:Buffer,mime:string){if(!data.length||data.length>MAX_FILE_BYTES)return{ok:false as const,error:"FILE_SIZE_INVALID"};const signatures:Record<string,(b:Buffer)=>boolean>={"application/pdf":b=>b.subarray(0,5).toString()==="%PDF-","image/jpeg":b=>b.length>=3&&b[0]===0xff&&b[1]===0xd8&&b[2]===0xff,"image/png":b=>b.length>=8&&b.subarray(0,8).equals(Buffer.from([0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a])),"image/webp":b=>b.length>=12&&b.subarray(0,4).toString()==="RIFF"&&b.subarray(8,12).toString()==="WEBP"};const head=data.subarray(0,512).toString("utf8").trimStart().toLowerCase();if(head.startsWith("<html")||head.startsWith("<!doctype html")||head.startsWith("<script")||head.startsWith("mz"))return{ok:false as const,error:"FILE_CONTENT_REJECTED"};if(!signatures[mime]?.(data))return{ok:false as const,error:"FILE_TYPE_MISMATCH"};return{ok:true as const,sha256:createHash("sha256").update(data).digest("hex"),scanStatus:"clean" as const}}
export function accessReason(req:FastifyRequest){const raw=req.headers["x-access-reason"];const reason=(Array.isArray(raw)?raw[0]??"":raw??"").trim();return reason.length>=3&&reason.length<=500?reason:null}
export async function recordSensitiveAccess(req:FastifyRequest,familyId:string,resourceType:string,resourceId:string,reason:string,db:PoolClient|typeof pool=pool){await db.query("INSERT INTO sensitive_access_logs(actor_id,family_id,resource_type,resource_id,action,access_reason,ip_address,user_agent)VALUES($1,$2,$3,$4,'download',$5,$6,$7)",[req.actor!.id,familyId,resourceType,resourceId,reason,req.ip,String(req.headers["user-agent"]??"").slice(0,500)]);await db.query("INSERT INTO audit_logs(actor_id,action,entity_type,entity_id,details)VALUES($1,'sensitive.access','family',$2,$3)",[req.actor!.id,familyId,{resourceType,resourceId,reason,action:"download"}])}
export async function securityEvent(eventType:string,req:FastifyRequest,details:Record<string,unknown>={},actorId:string|null=null,username:string|null=null,severity:"info"|"warning"|"critical"="warning"){await pool.query("INSERT INTO security_events(actor_id,username,event_type,severity,ip_address,user_agent,details)VALUES($1,$2,$3,$4,$5,$6,$7)",[actorId,username,eventType,severity,req.ip,String(req.headers["user-agent"]??"").slice(0,500),details])}
